- name: Install web component
  hosts: frontend
  become: yes
  tasks:
    - name: Install NGINX
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Start and enable NGINX
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default HTML directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create new HTML directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download web artifact
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip 
        dest: /tmp/frontend.zip

    - name: Extract web artifact
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy Roboshop NGINX configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted