- name: Install mysql-server
  hosts: mysql
  become: true
  tasks:
    - name: Installation of mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

    - name: Install PyMySQL (required for Ansible MySQL modules)
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3

    - name: Ensure MySQL root user has password
      community.mysql.mysql_user:
        name: root
        host: "mysql.joindevops.fun"
        password: "ExpenseApp@1"
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present

