
- name: Install and Secure MySQL
  hosts: mysql
  become: true
  tasks:
    - name: Install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

    - name: Set root password
      ansible.builtin.mysql_user:
        name: root
        password: "ExpenseApp@1"
        host_all: true
        login_unix_socket: /var/lib/mysql/mysql.sock
